export interface MenuItem {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  category: string;
  desc: string;
  image: string;
  emoji: string;
  isPopular?: boolean;
}

export interface MenuCategory {
  category: string;
  emoji: string;
  items: MenuItem[];
}

export const MENU_CATEGORIES: MenuCategory[] = [
  {
    category: "Special Combos",
    emoji: "🎁",
    items: [
      {
        id: "combo-1",
        name: "Regular Combo",
        price: 150,
        originalPrice: 190,
        category: "Special Combos",
        desc: "1 Regular Pizza + Cheese Burger + 250ml Coke",
        image: "/images/menu/regular-combo.jpg",
        emoji: "🍕",
        isPopular: true,
      },
      {
        id: "combo-2",
        name: "Double Cheese Family Combo",
        price: 350,
        originalPrice: 420,
        category: "Special Combos",
        desc: "2 Reg. Double Cheese Pizza with Mozzarella Cheese + 2 Cheese Burger + 1 Sandwich + 500ml Coke",
        image: "/images/menu/double-cheese-combo.jpg",
        emoji: "🍕",
        isPopular: true,
      },
      {
        id: "combo-3",
        name: "Party Feast Combo",
        price: 500,
        originalPrice: 550,
        category: "Special Combos",
        desc: "1 Medium Pizza + 1 Stuffed Garlic Bread with Cheese Dip + 1 Choco Lava Cake + 1 French Fries + 500ml Coke",
        image: "/images/menu/party-feast-combo.jpg",
        emoji: "🍕",
        isPopular: true,
      },
    ],
  },
  {
    category: "Burgers",
    emoji: "🍔",
    items: [
      {
        id: "burger-1",
        name: "Potato Burger",
        price: 30,
        category: "Burgers",
        desc: "Crispy potato patty with fresh veggies & special house sauce in soft sesame bun",
        image: "/images/menu/potato-burger.jpg",
        emoji: "🍔",
      },
      {
        id: "burger-2",
        name: "Veg Burger",
        price: 40,
        category: "Burgers",
        desc: "Fresh mixed vegetable patty loaded with lettuce, tomato & creamy mayo",
        image: "/images/menu/veg-burger.jpg",
        emoji: "🍔",
      },
      {
        id: "burger-3",
        name: "Cheese Burger",
        price: 50,
        category: "Burgers",
        desc: "Crispy veg patty topped with rich melted cheese slice & tangy mayonnaise",
        image: "/images/menu/cheese-burger.jpg",
        emoji: "🍔",
        isPopular: true,
      },
      {
        id: "burger-4",
        name: "Paneer Burger",
        price: 70,
        category: "Burgers",
        desc: "Grilled marinated paneer patty with spicy schezwan mayo & fresh onion rings",
        image: "/images/menu/paneer-burger.jpg",
        emoji: "🍔",
        isPopular: true,
      },
    ],
  },
  {
    category: "Pizzas",
    emoji: "🍕",
    items: [
      {
        id: "pizza-1",
        name: "Onion Capsicum Pizza",
        price: 65,
        category: "Pizzas",
        desc: "Crunchy red onions & fresh green capsicum on rich tomato sauce with mozzarella",
        image: "/images/menu/onion-capsicum-pizza.jpg",
        emoji: "🍕",
      },
      {
        id: "pizza-2",
        name: "Corn Topping Pizza",
        price: 75,
        category: "Pizzas",
        desc: "Juicy golden sweet corn sprinkled with Italian herbs & loaded mozzarella cheese",
        image: "/images/menu/corn-topping-pizza.jpg",
        emoji: "🍕",
      },
      {
        id: "pizza-3",
        name: "Babli Special Topping Pizza",
        price: 80,
        category: "Pizzas",
        desc: "Chef's signature pizza loaded with paneer, capsicum, onion, corn & secret spices",
        image: "/images/menu/babli-special-pizza.jpg",
        emoji: "🍕",
        isPopular: true,
      },
      {
        id: "pizza-4",
        name: "Margherita Pizza",
        price: 99,
        category: "Pizzas",
        desc: "Classic Italian style pizza with fresh tomato basil sauce & pure melted mozzarella",
        image: "/images/menu/margherita-pizza.jpg",
        emoji: "🍕",
      },
      {
        id: "pizza-5",
        name: "Double Cheese Pizza",
        price: 129,
        category: "Pizzas",
        desc: "Loaded double layer mozzarella cheese burst pizza for ultimate cheese lovers",
        image: "/images/menu/double-cheese-pizza.jpg",
        emoji: "🍕",
        isPopular: true,
      },
    ],
  },
  {
    category: "Pasta",
    emoji: "🍝",
    items: [
      {
        id: "pasta-1",
        name: "Red Sauce Pasta",
        price: 90,
        category: "Pasta",
        desc: "Penne pasta tossed in spicy & tangy Italian tomato garlic arrabbiata sauce",
        image: "/images/menu/red-sauce-pasta.jpg",
        emoji: "🍝",
      },
      {
        id: "pasta-2",
        name: "White Sauce Pasta",
        price: 100,
        category: "Pasta",
        desc: "Rich creamy Alfredo penne pasta with garlic, butter & melted cheese blend",
        image: "/images/menu/white-sauce-pasta.jpg",
        emoji: "🍝",
        isPopular: true,
      },
      {
        id: "pasta-3",
        name: "Mix Sauce Pasta",
        price: 110,
        category: "Pasta",
        desc: "Creamy pink sauce pasta combining rich Alfredo & zesty tomato sauce with veggies",
        image: "/images/menu/mix-sauce-pasta.jpg",
        emoji: "🍝",
      },
      {
        id: "pasta-4",
        name: "Cheese Pasta",
        price: 130,
        category: "Pasta",
        desc: "Extra cheesy penne pasta baked with double mozzarella & oregano herb seasoning",
        image: "/images/menu/cheese-pasta.jpg",
        emoji: "🍝",
        isPopular: true,
      },
    ],
  },
  {
    category: "Maggi",
    emoji: "🍜",
    items: [
      {
        id: "maggi-1",
        name: "Plain Masala Maggi",
        price: 50,
        category: "Maggi",
        desc: "Classic street-style Indian masala Maggi noodles prepared fresh & piping hot",
        image: "/images/menu/plain-masala-maggi.jpg",
        emoji: "🍜",
      },
      {
        id: "maggi-2",
        name: "Cheese Veggie Maggi",
        price: 70,
        category: "Maggi",
        desc: "Masala Maggi loaded with crunchy veggies & covered with melted cheese",
        image: "/images/menu/cheese-veggie-maggi.jpg",
        emoji: "🍜",
        isPopular: true,
      },
    ],
  },
  {
    category: "Fries",
    emoji: "🍟",
    items: [
      {
        id: "fries-1",
        name: "French Fries",
        price: 40,
        category: "Fries",
        desc: "Golden salted crispy potato french fries served hot with tomato ketchup",
        image: "/images/menu/french-fries.jpg",
        emoji: "🍟",
      },
      {
        id: "fries-2",
        name: "Peri Peri French Fries",
        price: 60,
        category: "Fries",
        desc: "Crispy golden potato fries tossed in fiery African Peri Peri spice mix",
        image: "/images/menu/peri-peri-fries.jpg",
        emoji: "🍟",
        isPopular: true,
      },
    ],
  },
  {
    category: "Side Orders",
    emoji: "🥪",
    items: [
      {
        id: "side-1",
        name: "Sandwich",
        price: 40,
        category: "Side Orders",
        desc: "Golden grilled sandwich stuffed with fresh vegetables & tangy mint mayo",
        image: "/images/menu/sandwich.jpg",
        emoji: "🥪",
      },
      {
        id: "side-2",
        name: "Zingy Cheese Parcel",
        price: 50,
        category: "Side Orders",
        desc: "Oven baked golden bread parcel filled with spicy paneer & melted cheese",
        image: "/images/menu/zingy-cheese-parcel.jpg",
        emoji: "🥪",
      },
      {
        id: "side-3",
        name: "Cheese Bomb",
        price: 60,
        category: "Side Orders",
        desc: "Crispy breaded bites stuffed with gooey liquid melted cheese that explodes in your mouth",
        image: "/images/menu/cheese-bomb.jpg",
        emoji: "🧆",
        isPopular: true,
      },
      {
        id: "side-4",
        name: "Choco Lava Cake",
        price: 69,
        category: "Side Orders",
        desc: "Warm dark chocolate cake with rich oozing molten liquid chocolate center",
        image: "/images/menu/choco-lava-cake.jpg",
        emoji: "🧁",
        isPopular: true,
      },
      {
        id: "side-5",
        name: "Garlic Bread",
        price: 70,
        category: "Side Orders",
        desc: "Freshly baked garlic butter bread sticks topped with aromatic herbs",
        image: "/images/menu/garlic-bread.jpg",
        emoji: "🥖",
      },
      {
        id: "side-6",
        name: "Stuffed Garlic Bread",
        price: 90,
        category: "Side Orders",
        desc: "Garlic bread stuffed with golden sweet corn, jalapeños & melted mozzarella cheese",
        image: "/images/menu/stuffed-garlic-bread.jpg",
        emoji: "🥖",
        isPopular: true,
      },
      {
        id: "side-7",
        name: "Calzone Pocket",
        price: 99,
        category: "Side Orders",
        desc: "Folded Italian pizza pocket baked to golden perfection with spicy cheese veggie filling",
        image: "/images/menu/calzone-pocket.jpg",
        emoji: "🥟",
      },
    ],
  },
  {
    category: "Coffee & Shakes",
    emoji: "🥤",
    items: [
      {
        id: "drink-1",
        name: "Butterscotch Shake",
        price: 59,
        category: "Coffee & Shakes",
        desc: "Smooth creamy butterscotch thick shake topped with caramel syrup & crunchies",
        image: "/images/menu/butterscotch-shake.jpg",
        emoji: "🥤",
      },
      {
        id: "drink-2",
        name: "Cold Coffee",
        price: 69,
        category: "Coffee & Shakes",
        desc: "Chilled espresso coffee blended with creamy milk & vanilla ice cream",
        image: "/images/menu/cold-coffee.jpg",
        emoji: "☕",
        isPopular: true,
      },
      {
        id: "drink-3",
        name: "Oreo Shake",
        price: 79,
        category: "Coffee & Shakes",
        desc: "Thick chilled shake blended with chocolate Oreo cookies & topped with cookie crumbs",
        image: "/images/menu/oreo-shake.jpg",
        emoji: "🥤",
        isPopular: true,
      },
      {
        id: "drink-4",
        name: "Chocolate Shake",
        price: 79,
        category: "Coffee & Shakes",
        desc: "Indulgent Belgian dark chocolate thick shake garnished with chocolate fudge",
        image: "/images/menu/chocolate-shake.jpg",
        emoji: "🥤",
      },
      {
        id: "drink-5",
        name: "KitKat Shake",
        price: 89,
        category: "Coffee & Shakes",
        desc: "Crispy KitKat wafer chocolate bars blended into a creamy rich shake",
        image: "/images/menu/kitkat-shake.jpg",
        emoji: "🥤",
        isPopular: true,
      },
      {
        id: "drink-6",
        name: "Lassi",
        price: 50,
        category: "Coffee & Shakes",
        desc: "Traditional chilled sweet yoghurt drink prepared fresh in sweet Punjabi style",
        image: "/images/menu/lassi.jpg",
        emoji: "🥛",
      },
      {
        id: "drink-7",
        name: "Special Lassi",
        price: 80,
        category: "Coffee & Shakes",
        desc: "Rich thick Punjabi lassi topped with fresh malai, crushed almonds, cashews & pistachio",
        image: "/images/menu/special-lassi.jpg",
        emoji: "🥛",
        isPopular: true,
      },
      {
        id: "drink-8",
        name: "Soft Drink",
        price: 20,
        category: "Coffee & Shakes",
        desc: "Chilled 250ml soft drink (Coke, Thums Up, Sprite) served ice-cold",
        image: "/images/menu/soft-drink.jpg",
        emoji: "🥤",
      },
    ],
  },
];
